services:
  postgres:
    container_name: postgres_sql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - spring-boot-network

  spring-boot-app:
    container_name: springboot
    image: postgres-springboot
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  spring-boot-network:
    driver: bridge
    

